/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:8bbd6ae6-dd1a-4f76-8599-0d0bac4a30cd",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_VAqUJzr8Q",
    "aws_user_pools_web_client_id": "3jut7mmg9u6qv51fj98i2ogiok",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "aws_user_files_s3_bucket": "mynextapponamplify1140557-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
